# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for upgrade-carbonio-packages
- ansible.builtin.import_tasks: upgrade-carbonio.yml
