# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Fix memcached config
    become: true
    become_method: su
    become_user: zextras
    command: '/opt/zextras/bin/carbonio prov -l ms {{ inventory_hostname }} zimbraMemcachedBindAddress "" '
    when: inventory_hostname in groups["proxyServers"] and (groups['filesServers'] | length > 0 or groups['docsServers'] | length > 0 or groups['previewServers'] | length > 0)
    tags:
      - fix-config 