# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for post_carbonio_packages_upgrade
- ansible.builtin.import_tasks: remove_unused_dependencies.yml
- ansible.builtin.import_tasks: execute_config_fixes.yml
- ansible.builtin.import_tasks: execute_carbonio_pending_setups.yml
- ansible.builtin.import_tasks: execute_dbconnectors_bootstrap.yml
- ansible.builtin.import_tasks: restart_carbonio_services.yml
