# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for pre-carbonio-upgrade
- ansible.builtin.import_tasks: validate_password_files.yml
- ansible.builtin.import_tasks: validate_inventory_chats.yml
- ansible.builtin.import_tasks: validate_inventory_values.yml
- ansible.builtin.import_tasks: create_pre_upgrade_backups.yml
- ansible.builtin.import_tasks: validate_rsyslog_config.yml
- ansible.builtin.import_tasks: validate_carbonio_version.yml
