# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# tasks file for pre-carbonio-upgrade
- import_tasks: password-checks.yml
- import_tasks: chats_check.yml
- import_tasks: ansible_controller_dependencies.yml
- import_tasks: inventory_values_checks.yml
- import_tasks: pre-upgrade-cmds.yml
- import_tasks: rsyslog-config-check.yml
