# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
- name: Check if Consul password file exists
  ansible.builtin.stat:
    path: "{{ inventory_file }}_consulpassword"
  delegate_to: localhost
  run_once: true
  register: consul_password_file 

- name: Fail if Consul password file does not exist
  ansible.builtin.fail:
    msg: "Consul password file {{ inventory_file }}_consulpassword was not found. Please place it in the same directory as the inventory file. "
  run_once: true
  when: not consul_password_file.stat.exists

- name: Check if Postgres password file exists 
  ansible.builtin.stat:
    path: "{{ inventory_file }}_postgrespassword"
  delegate_to: localhost
  run_once: true
  register: postgres_password_file

- name: Fail if Postgres password file does not exist 
  ansible.builtin.fail:
    msg: "Postgres password file '{{ inventory_file }}_postgrespassword' was not found. Please place it in the same directory as the inventory file."
  run_once: true
  when: not postgres_password_file.stat.exists