# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
# handlers file for post-carbonio-packages-upgrade
- name: restart_carbonio_services
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ carbonio_services_in_memory.stdout_lines }}"