# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install Memcached on Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ memcached_packages }}"
    when: ansible_facts.os_family == "Debian" and inventory_hostname in groups["proxyServers"][0]
    tags:
      - install-carbonio-memcached

######## RHEL
  - name: Install Memcached on RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ memcached_packages }}"
    when: (ansible_facts.os_family == "RedHat" or ansible_facts.os_family == "CentOS") and inventory_hostname in groups["proxyServers"][0]
    tags:
      - install-carbonio-memcached