# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
  - name: Install videorecorder db connector Ubuntu
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ videorecorder_dbconnectors_packages }}"
    when: 
      - ansible_facts.os_family == "Debian"
      - (
          (inventory_hostname in groups['postgresServers'][0] and groups['dbsConnectorServers'] | length == 0) or 
          (groups['dbsConnectorServers'] | length > 0 and inventory_hostname in groups['dbsConnectorServers'][0] and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
        )
      - groups['videoServers'] | length > 0 
    tags:
      - install-carbonio-dbconnectors
      - install-carbonio-videoserver

      
##### RHEL
  - name: Install videorecorder db connector RHEL
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ videorecorder_dbconnectors_packages }}"
    when: 
      - ansible_facts.os_family == "RedHat" or ansible_facts.os_family == "CentOS"
      - (
          (inventory_hostname in groups['postgresServers'][0] and groups['dbsConnectorServers'] | length == 0) or 
          (groups['dbsConnectorServers'] | length > 0 and inventory_hostname in groups['dbsConnectorServers'][0] and groups['dbsConnectorServers'][0] != groups['postgresServers'][0])
        ) 
      - groups['videoServers'] | length > 0 
    tags:
      - install-carbonio-dbconnectors
      - install-carbonio-videoserver