# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
#   - name: Install Carbonio Catalog  24.9 -> 24.12 [Ubuntu]
#     become: true
#     apt: name={{ item }} state=present
#     with_items:
#       - "{{ catalog_packages }}"        
#     when: ansible_os_family == "Debian"  and inventory_hostname in groups["proxyServers"] 
#     tags:
#       - install-carbonio-catalog
  

# ######## RHEL
#   - name: Install Carbonio Catalog  24.9 -> 24.12 [RHEL]
#     become: true
#     yum: name={{ item }} state=present
#     with_items:
#       - "{{ catalog_packages }}"        
#     when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["proxyServers"] 
#     tags:
#       - install-carbonio-catalog

- name: Check if Carbonio Catalog service is present in Consul
  become: true
  command: "consul catalog services | grep -q {{ item }}"
  with_items:
    - "{{ catalog_packages }}"
  register: check_catalog
  changed_when: false
  failed_when: false
  # Проверяем только на определенных хостах (пример — если catalog ставится на proxyServers)
  when: inventory_hostname in groups["proxyServers"]
  tags:
    - install-carbonio-catalog

- name: Debug if Carbonio Catalog is already installed
  debug:
    msg: "Carbonio Catalog is already installed according to Consul"
  when:
    - check_catalog.rc == 0
    - inventory_hostname in groups["proxyServers"]
  tags:
    - install-carbonio-catalog

- name: Install Carbonio Catalog 24.9 -> 24.12 [Ubuntu]
  become: true
  apt: name={{ item }} state=present
  with_items:
    - "{{ catalog_packages }}"    
  when:
    - check_catalog.rc == 1
    - ansible_os_family == "Debian"
    - inventory_hostname in groups["proxyServers"]
  tags:
    - install-carbonio-catalog

- name: Install Carbonio Catalog 24.9 -> 24.12 [RHEL]
  become: true
  yum: name={{ item }} state=present
  with_items:
    - "{{ catalog_packages }}" 
  when:
    - check_catalog.rc == 1
    - ansible_os_family in ["RedHat", "CentOS"]
    - inventory_hostname in groups["proxyServers"]
  tags:
    - install-carbonio-catalog