# SPDX-FileCopyrightText: 2024 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only

---
#   - name: Install carbonio-storages 24.3 -> 24.5 [Ubuntu]
#     become: true
#     apt: name={{ item }} state=present
#     with_items:
#       - "{{ carbonio_storages_packages }}"
#     when: ansible_os_family == "Debian" and inventory_hostname in groups["dbsConnectorServers"] and groups['filesServers'] | length > 0
#     tags:
#       - install-carbonio-storages

# ##### RHEL

#   - name: Install carbonio-storages 24.3 -> 24.5 [RHEL]
#     become: true
#     yum: name={{ item }} state=present
#     with_items:
#       - "{{ carbonio_storages_packages }}"
#     when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["dbsConnectorServers"] and groups['filesServers'] | length > 0
#     tags:
#       - install-carbonio-storages

  - name: Remove storages 24.9 -> 24.12 [Ubuntu]
    become: true
    apt: name={{ item }} state=absent
    with_items:
      - "{{ carbonio_storages_packages }}"
    when: ansible_os_family == "Debian" and inventory_hostname in groups["dbsConnectorServers"] and groups['filesServers'] | length > 0
    tags:
      - upgrade-carbonio-storages

  - name: Install carbonio storages  24.9 -> 24.12 [Ubuntu]
    become: true
    apt: name={{ item }} state=present
    with_items:
      - "{{ carbonio_storages_packages }}"
    when: ansible_os_family == "Debian" and inventory_hostname in groups['filesServers']
    tags:
      - upgrade-carbonio-storages

##### RHEL

  - name: Remove carbonio storages  24.9 -> 24.12 [RHEL]
    become: true
    yum: name={{ item }} state=absent
    with_items:
      - "{{ carbonio_storages_packages }}"
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups["dbsConnectorServers"] and groups['filesServers'] | length > 0
    tags:
      - upgrade-carbonio-storages

  - name: Install carbonio storages  24.9 -> 24.12 [RHEL]
    become: true
    yum: name={{ item }} state=present
    with_items:
      - "{{ carbonio_storages_packages }}"
    when: (ansible_os_family == "RedHat" or ansible_os_family == "CentOS") and inventory_hostname in groups['filesServers']
    tags:
      - upgrade-carbonio-storages

##### Common

  - name: Reset failed services
    shell:
      cmd: 'systemctl reset-failed'
      executable: /bin/bash
    when: inventory_hostname in groups['filesServers']
    tags:
      - upgrade-carbonio-storages