# SPDX-FileCopyrightText: Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: GPL-3.0-only
---
- name: Confirm Carbonio upgrade
  hosts: all
  order: inventory
  gather_facts: true
  any_errors_fatal: true
  roles:
    - ../roles/confirm_upgrade

- name: Prepare Ansible controller
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - ../roles/prepare_ansible_controller

- name: Run pre-upgrade validation and backups
  hosts: all
  order: inventory
  gather_facts: true
  roles:
    - ../roles/pre_carbonio_upgrade

- name: Upgrade PostgreSQL and master/replica Directory servers
  hosts: postgresServers, masterDirectoryServers, replicaDirectoryServers
  serial: 1
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/install_new_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade remaining Service Discover servers
  hosts: serviceDiscoverServers, !masterDirectoryServers, !replicaDirectoryServers
  serial: 1
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/install_new_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade DB Connector servers
  hosts: dbsConnectorServers
  serial: 1
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/install_new_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade remaining Application servers
  hosts: applicationServers, !dbsConnectorServers
  serial: 1
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade Files servers
  hosts: filesServers
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/install_new_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade Proxy servers
  hosts: proxyServers
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/install_new_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade Chats servers
  hosts: workStreamServers
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/install_new_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade Video servers
  hosts: videoServers
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Upgrade remaining Carbonio servers
  hosts: all, !serviceDiscoverServers, !masterDirectoryServers, !replicaDirectoryServers, !dbsConnectorServers, !applicationServers, !filesServers, !proxyServers, !workStreamServers, !videoServers
  order: inventory
  gather_facts: true
  roles:
    - ../roles/upgrade_carbonio_packages
    - ../roles/post_carbonio_packages_upgrade

- name: Verify Carbonio services after upgrade
  hosts: all
  order: inventory
  gather_facts: true
  roles:
    - ../roles/chk_carbonio_upgrade
